services:

  backend:
    build: ./backend
    container_name: construction_backend
    ports:
      - "3000:3000"
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: construction_db
    depends_on:
      - mysql

  frontend:
    build: ./frontend
    container_name: construction_frontend
    ports:
      - "8081:80"
    depends_on:
      - backend

  mysql:
    image: mysql:8.0
    container_name: construction_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: construction_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
